### ISSUE TITLE
Is there an ability to use this on 1.20?

### ISSUE THREAD

**Issue by lilynet336** [Sxtanna/keybind-presets#3]
Hi! I just got a controller that causes me to have the need for sets of key binds, hence this mod. I can't find any other mods like it, but this mod is for 1.19.4. It does load on 1.20, but clicking Presets does nothing. Is there any way for me to fix this? Thank you!

**Comment by Sxtanna** [comment]
addressed in #5

see:
- https://github.com/Sxtanna/keybind-presets/releases
or
- https://modrinth.com/mod/keybind-presets/versions
